Adding DPT 10 and DPT 11
estbeetoo/node-red-contrib-knx pull request #27
Opened 2019-02-18 19:51 UTC by evlas

Passing timestamp to the DPT10 and DPT11, the correct KNX package is generated

2019-02-21 10:46 UTC, aborovsky requested changes
Thank you a lot for PR!
It's great and i like your idea to accept and handle time as timestamp. It's pretty comfort for JS environment.

I've merged concurrent PR: https://github.com/estbeetoo/node-red-contrib-knx/pull/22/files
There implemented DPT10, but incoming data must be a structure: `{ "day": 3, "hours": 11, "minutes": 22, "seconds": 44 }, "dpt": "10" }`

I propose to support both alternatives for DPT10: incoming data may be a structure or just a plain timestamp.

Also, i'd like to ask you to improve knx.html knx-out node's online readme: add DTP10 and DPT11 message format type. As it was done here: [knx.html improvement](https://github.com/estbeetoo/node-red-contrib-knx/commit/208ca95b68f394a217cf6cce757e246db97be1d5#diff-ab0080e7c56d0c8800e08c27a674f53eR94)

Please, improve your PR.

2019-02-21 10:46 UTC, aborovsky commented on knx.js
> +                case '10':   //3Byte fron timestamp
typo in `fron` :)

2019-02-21 10:46 UTC, aborovsky commented on knx.js
> +                case '10':   //3Byte fron timestamp
May i ask you to provide few test cases for both DPT10 and DPT11?
For example:
`1550745501013` -> `Buffer[ 141, 38, 21 ]`

I'll add unit tests on the base of Mocha + ChaiJS

2019-02-21 19:46 UTC, evlas commented
Hello,
sorry, I do not know Mocha and ChalJS.
I generated 2 files to test DPT10 and DPT11.

Il giorno gio 21 feb 2019 alle ore 11:46 Alexander Borovsky <
notifications@github.com> ha scritto:

> *@aborovsky* requested changes on this pull request.
>
> Thank you a lot for PR!
> It's great and i like your idea to accept and handle time as timestamp.
> It's pretty comfort for JS environment.
>
> I've merged concurrent PR:
> https://github.com/estbeetoo/node-red-contrib-knx/pull/22/files
> There implemented DPT10, but incoming data must be a structure: { "day":
> 3, "hours": 11, "minutes": 22, "seconds": 44 }, "dpt": "10" }
>
> I propose to support both alternatives for DPT10: incoming data may be a
> structure or just a plain timestamp.
>
> Please, improve your PR.
> ------------------------------
>
> In knx.js
> <https://github.com/estbeetoo/node-red-contrib-knx/pull/27#discussion_r258869105>
> :
>
> > @@ -207,6 +207,40 @@ module.exports = function (RED) {
>                      buf.writeFloatLE(value, 0);
>                      value = buf;
>                      break;
> +                case '10':   //3Byte fron timestamp
>
> typo in fron :)
> ------------------------------
>
> In knx.js
> <https://github.com/estbeetoo/node-red-contrib-knx/pull/27#discussion_r258871899>
> :
>
> > @@ -207,6 +207,40 @@ module.exports = function (RED) {
>                      buf.writeFloatLE(value, 0);
>                      value = buf;
>                      break;
> +                case '10':   //3Byte fron timestamp
>
> May i ask you to provide few test cases for both DPT10 and DPT11?
> For example:
> 1550745501013 -> Buffer[ 141, 38, 21 ]
>
> I'll add unit tests on the base of Mocha + ChaiJS
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/estbeetoo/node-red-contrib-knx/pull/27#pullrequestreview-206230749>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGrLUp3uZ0lgu34IbwZjpXQMSgGmInpks5vPnkYgaJpZM4bBhEI>
> .
>

2019-02-24 18:05 UTC, evlas commented
Hello,
I have mixed my code with yours

2019-03-17 15:34 UTC, aborovsky commented
@evlas thank you for improvements! But there are still unresolved conflicts. May i ask you to resolve them?

2020-05-24 12:56 UTC, merged